### ISSUE TITLE
Error index

### ISSUE THREAD

**Issue by robmsmt** [SngLol/PythonMenuSetup#1]
```
Traceback (most recent call last):
  File "run.py", line 182, in <module>
    a.run()
  File "run.py", line 164, in run
    if self.getCon(self.alt[str(i)][2], self.alt[str(i)][3]) == True:
IndexError: list index out of range
```

Using ubuntu on examples on readme. If i then change indexes to:
`    if self.getCon(self.alt[str(i)][0], self.alt[str(i)][1]) == True:`

I get:

```
    attrs_save = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')

```

**Comment by SngLol** [comment]
It's all fixed, finally
I've added "conditions" to the MenuSetup.
